name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-terraform:
    name: Lint Terraform code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Lint Terraform code
        run: terraform fmt -check -diff -recursive

      - name: Initialize Terraform (offline only)
        run: terraform init -backend=false

      - name: Validate Terraform code
        run: terraform validate
